name: End to End Testing

on:
  # https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
  # pull_request_target is potentially dangerous target so we keep it strict
  # under the label and benefit from secret propagation
  pull_request_target:
    types:
      - synchronize
      - labeled

env:
  UP_API_TOKEN: ${{ secrets.UP_E2E_API_TOKEN || secrets.UP_API_TOKEN }}
  UP_ORG: ${{ secrets.UP_E2E_ORG || secrets.UP_ORG }}
  UP_GROUP: ${{ secrets.UP_E2E_GROUP || secrets.UP_GROUP || 'default' }}
  UP_ROBOT_ID: ${{ secrets.UP_E2E_ROBOT_ID || secrets.UP_ROBOT_ID }}
  ROUTE53_ZONE_ID: ${{ secrets.E2E_ROUTE53_ZONE_ID }}
  IAM_ROLE_ARN: ${{ secrets.E2E_IAM_ROLE_ARN }}

jobs:
  e2e:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Export project-specific environment variables
        if: secrets.E2E_EXTRA != ''
        env:
          E2E_EXTRA: ${{ secrets.E2E_EXTRA }}
        run: |
          echo "$E2E_EXTRA" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
          
      - name: Install and login with up
        if: env.UP_API_TOKEN != '' && env.UP_ORG != ''
        uses: upbound/action-up@53fe6395637d884c80d2bbc8c2d75d0ece776ced # v1
        with:
          api-token: ${{ env.UP_API_TOKEN }}
          organization: ${{ env.UP_ORG }}

      # doesn't work with plain token when pushing otherwise
      - name: Login to xpkg with robot
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: xpkg.upbound.io
          username: ${{ env.UP_ROBOT_ID }}
          password: ${{ env.UP_API_TOKEN }}

      - name: Build project
        run: up project build

      - name: Switch up context
        run: up ctx ${{ env.UP_ORG }}/upbound-gcp-us-central-1/${{ env.UP_GROUP }}

      - name: Run e2e tests
        run: |
          if [ -n "$ROUTE53_ZONE_ID" ] && [ -n "$IAM_ROLE_ARN" ]; then
            up test run tests/* --e2e -D route53ZoneId=${{ env.ROUTE53_ZONE_ID }} -D iamRoleArn=${{ env.IAM_ROLE_ARN }}
          else
            echo "Warning: Using default values. Set E2E_ROUTE53_ZONE_ID and E2E_IAM_ROLE_ARN secrets for custom values."
            up test run tests/* --e2e
          fi
